version: '3.9'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - db_data:/var/lib/mongo
  my-node-app:
    image: com.andriidnikitin.tickets/tickets-api-js
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - NODE_PORT=3000
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
volumes:
  db_data: